### ISSUE TITLE
Volume does not match the ingame volume

### ISSUE THREAD

**Issue by ReneRebsdorf** [B3none/cs2-clutch-announce#22]
The announcements are quite loud, and does not adhere to the volume as per the volume command.

Is it possible to implement this?

**Comment by NikolaJyun** [comment]
in config add
  "snd_toolvolume": 0.25, default:1
in game console
snd_toolvolume 1 (default:1)

**Comment by ReneRebsdorf** [comment]
> in config add
> 
>   "snd_toolvolume": 0.25, default:1
> 
> in game console
> 
> snd_toolvolume 1 (default:1)

Thank you for the reply.
Am I understanding it correctly, that this is a client side configuration, and not adjustable server side? 
I was hoping to be able to adjust its relative volume.
